### ISSUE TITLE
Spike in Tracks after dump restart

### ISSUE THREAD

**Issue by Andechs75** [wiedehopf/graphs1090#27]
Hi there,
everytime i restart the dump-service, i get a hughe spike in the "ADS-B Tracks Seen" with more than one message. Is there any possibility to prevent this? 
I think its like startup with a bunch of old data. So that counts in Msg per second and spikes the graph.

**Comment by wiedehopf** [comment]
That's a limitation in how the stats.json is written by dump1090-fa.
On a restart every previous track is counted as new track again and the number transitions from 0 to the current number of received aircraft.
collectd notes down the rate of increase.

I've circumvented that issue in readsb by writing the first stats.json 10 seconds after startup so the number is already roughly the number of received aircraft.
But due to how collectd processes the data only the difference to the last value is important (it's discarded if the counter decreases as it does on restart)

https://github.com/wiedehopf/readsb

I don't have a viable solution i could implement in graph1090 thus i'll close this issue .. can't fix.
