### ISSUE TITLE
CPU Memory Temperature Graph Enhancements

### ISSUE THREAD

**Issue by tstolze** [wiedehopf/graphs1090#6]
Would it be possible to get some details on the CPU Utilization, Temperature, and maybe the Memory Graphs like some of the other graphs showing high/low/average, it doesn't have to be graphed, just text reports at the bottom of the graph.    Thanks

**Comment by wiedehopf** [comment]
I'll do it for the temperature.

Memory is logged in an useless way anyway, so you don't really gain anything from numbers for that.

CPU i might do an average but no min or max because doing that properly requires 20 lines and i don't really see the use.

**Comment by wiedehopf** [comment]
Have a look, it's pushed out.

**Comment by wiedehopf** [comment]
To elaborate on the memory: The portion marked as "cached" is comprised of files cached in memory, that cache can be reclaimed really fast and isn't indicative of how much memory is available.
Cached files also includes tmpfs ramdisks which can not be easily reclaimed.
So the way collectd logs memory is flawed anyway, numbers won't really tell you anything.
An "overall" memory usage as depicted here is meaningless because there is more free memory that you can see 99% of cases.

**Comment by tstolze** [comment]
Awesome and thank you!
Working on my system.  :)

**Comment by wiedehopf** [comment]
I'm changing the way memory is logged right now so the graph is actually useful.
I'll orient the graph on the htop memory display: https://stackoverflow.com/questions/41224738/how-to-calculate-system-memory-usage-from-proc-meminfo-like-htop

The memory graph will be wiped clean until new data is collected.
Still working on it though.
I'll probably include a current value as well and maybe a minimum of how much memory was available at peak usage.

**Comment by wiedehopf** [comment]
Check back, the memory graph now has some numbers below it.

And much improved.
